#!/usr/bin/env ksh
#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# PROGRAM:
#	~/.aliases
#	
# PURPOSE:
#	Defines some aliases
#	
# USAGE:
#	Invoked by ~/.profile at login.
#
#-------------------------------------------------------------------------------
alias a="amber"					    # Use Amber to generate bash scripts.
alias c="tput clear"			    # clear the screen
alias clr="tput clear"			    # clear the screen
alias dr="cd ~/Downloads/;ls -ltr"  # go to ~/Downloads, run ls -ltr
alias g="$(which git)"			    # short for git
alias get=g  					    # avoid common typo
alias gits="g status"			    # shorthand for 'git status'
alias gl="$(which git) log"		    # short for git log
alias gs="$(which git) status"	    # short for git status
alias h="fc -l"					    # history command for ksh
alias l="ls -l"					    # short for long list ls
alias ll="ls -l"				    # short for long list ls
alias lr="ls -ltr"				    # short for long list time reversed ls
alias print="echo"				    # bash has no print
alias vl="view logs/setup.log"	    # to view project setup log
# perltidy: use whichever perltidy is in PATH (works on ARM Mac, Intel Mac, Linux)
alias perltidy="$(which perltidy) -pro=~/.perltidyrc"
if [ "$(uname)" = "Darwin" ]; then
    alias python=/Users/steve/anaconda3/bin/python3.11
else
    alias python="$(which python3)"
fi
alias py=python
