#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#	~/.aliases
#	
# PURPOSE:
#	Defines some aliases
#	
# USAGE:
#	Invoked by ~/.profile at login.
#
#-------------------------------------------------------------------------------
alias c="tput clear"		# clear the screen
alias print="echo"			# bash has no print
alias clr="tput clear"		# clear the screen
alias h="fc -l"				# history command for ksh
alias l="ls -l"				# short for long list ls
alias ll="ls -l"			# short for long list ls
alias lr="ls -ltr"			# short for long list time reversed ls
alias py="$(which python)"	# short for python
alias g="$(which git)"		# short for git
alias gl="$(which git) log"	# short for git log
alias pbcopy='xsel --clipboard --input'		# copy text to clipboard
alias pbpaste='xsel --clipboard --output'	# paste text from clipboard
alias vl="view logs/setup.log"				# to view project setup log
alias get=git				# avoid common typo
