#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#   ~/.kshrc
#   
# PURPOSE:
#   This ksh script makes sure that when Terminal or xterm windows are spawned
#   that ~/.profile is invoked.
#   
# USAGE:
#   This is sourced with Terminal or xterm windows are spawned.
#-------------------------------------------------------------------------------
. ~/.profile
