#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#	~/.kshrc
#	
# PURPOSE:
#	This is a simple pass through that source ~/.profile.
#	
# USAGE:
#	source ~/.kshrc
#
#-------------------------------------------------------------------------------
#!/usr/bin/env ksh

. ~/.profile
