#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
#         Copyright (C) 2023    Steve Price    SuperStevePrice@gmail.com
#
#                       GNU GENERAL PUBLIC LICENSE
#                        Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#	.profile	
#	
# PURPOSE:
#	ksh profile
#	
# USAGE:
#	Invoked by the operating system at login.
#-------------------------------------------------------------------------------

# PS1: command line primary prompt:
. ~/bin/PS1.ksh

# load my aliases
. ~/.aliases

# load my functions
. ~/.functions

export HOST=$(uname -n)
export FCEDIT=vi

# Add to $PATH
PATH=$PATH:$HOME/bin:/usr/local/bin:$HOME/anaconda3/bin:.

# Remove dups from $PATH
export PATH=$(echo $PATH | awk -v RS=':' '!a[$0]++ {if (NR>1) printf(":"); printf("%s", $0)}')

export TERM=xterm

# Detect the operating system and set environment to run perl Tk modules.
if [ "$(uname)" == "Darwin" ]; then
    # macOS specific configurations.  Not required for Linux.
    eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
    eval $(/usr/local/bin/brew shellenv)
fi

set -o vi
