#!/usr/bin/env ksh

#-------------------------------------------------------------------------------
# Copyright (C) 2023 Steve Price SuperStevePrice@gmail.com
#
# GNU GENERAL PUBLIC LICENSE
# Version 3, 29 June 2007
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# PROGRAM:
#   .profile  
#   
# PURPOSE:
#   ksh profile
#   
# USAGE:
#   Invoked by the operating system at login.
#-------------------------------------------------------------------------------

# PS1: command line primary prompt:
. ~/bin/PS1.ksh

# load my aliases
. ~/.aliases

# load my functions
. ~/.functions

export HOST=$(uname -n)
export FCEDIT=vi

# Set the standard locations for common utilities
PATH="/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin"

# Add additional directories if needed
PATH="$PATH:/opt/X11/bin:/opt/homebrew/bin"
PATH="$PATH:$HOME/bin:$HOME/anaconda3/bin:."

# Remove duplicates from PATH
export PATH=$(echo $PATH | awk -v RS=':' '!a[$0]++ {if (NR>1) printf(":"); printf("%s", $0)}')

# Detect the operating system and set environment to run perl Tk modules.
if [ "$(uname)" == "Darwin" ]; then
    # macOS specific configurations. Not required for Linux.
    eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

    # If brew is installed, set the environment:
    brew=$(command -v brew)
    if [ -n "$brew" ]; then
        eval "$("$brew" shellenv)"
    fi
fi

# Setting the terminal type for xterm and Terminal windows. 
# term=xterm does not work for xterm vi sessions; vt100 does.
#export TERM=vt100
export TERM=xterm-256color

# Enable CLI editing of previous commands in history:
set -o vi
#-------------------------------------------------------------------------------
# Last installed: 2023-05-25 19:15:34
#-- End of File ----------------------------------------------------------------
