" Typo corrections, English & German -- insert-mode abbreviations
" Generated list; see Typo_Corrections.xlsx
iabbrev alot a lot
iabbrev albe able
iabbrev abotu about
iabbrev abuot about
iabbrev aobut about
iabbrev baout about
iabbrev accomadate accommodate
iabbrev accomodate accommodate
iabbrev acommodate accommodate
iabbrev acheive achieve
iabbrev accross across
iabbrev acros across
iabbrev actaully actually
iabbrev actulaly actually
iabbrev acutally actually
iabbrev atcually actually
iabbrev catually actually
iabbrev addres address
iabbrev adress address
iabbrev afetr after
iabbrev aftre after
iabbrev atfer after
iabbrev fater after
iabbrev aagin again
iabbrev agani again
iabbrev agian again
iabbrev gaain again
iabbrev aaginst against
iabbrev agaisnt against
iabbrev aganist against
iabbrev agianst against
iabbrev gaainst against
iabbrev aggresive aggressive
iabbrev agressive aggressive
iabbrev aog ago
iabbrev lal all
iabbrev alerady already
iabbrev alraedy already
iabbrev alreday already
iabbrev arleady already
iabbrev laready already
iabbrev alos also
iabbrev aslo also
iabbrev laso also
iabbrev alawys always
iabbrev alwasy always
iabbrev alwyas always
iabbrev awlays always
iabbrev laways always
iabbrev amatuer amateur
iabbrev amature amateur
iabbrev nad and
iabbrev anohter another
iabbrev anotehr another
iabbrev antoher another
iabbrev aonther another
iabbrev naother another
iabbrev ayn any
iabbrev antyhing anything
iabbrev anyhting anything
iabbrev anytihng anything
iabbrev aynthing anything
iabbrev naything anything
iabbrev aparent apparent
iabbrev apparant apparent
iabbrev apparrent apparent
iabbrev aer are
iabbrev aera area
iabbrev arae area
iabbrev raea area
iabbrev arguement argument
iabbrev arguemnt argument
iabbrev aorund around
iabbrev aronud around
iabbrev aroudn around
iabbrev aruond around
iabbrev raound around
iabbrev athiest atheist
iabbrev aawy away
iabbrev awya away
iabbrev waay away
iabbrev abck back
iabbrev bakc back
iabbrev bcak back
iabbrev bda bad
iabbrev baptisim baptism
iabbrev absed based
iabbrev baesd based
iabbrev basde based
iabbrev bsaed based
iabbrev basicaly basically
iabbrev basicly basically
iabbrev beatiful beautiful
iabbrev beautifull beautiful
iabbrev beutiful beautiful
iabbrev beacuse because
iabbrev becasue because
iabbrev becuase because
iabbrev bceause because
iabbrev ebcause because
iabbrev bene been
iabbrev befoer before
iabbrev befroe before
iabbrev beofre before
iabbrev bfeore before
iabbrev ebfore before
iabbrev beggining beginning
iabbrev begining beginning
iabbrev beign being
iabbrev benig being
iabbrev bieng being
iabbrev ebing being
iabbrev beleive believe
iabbrev beleve believe
iabbrev belive believe
iabbrev beileve believe
iabbrev belivee believe
iabbrev bleieve believe
iabbrev eblieve believe
iabbrev bset best
iabbrev ebst best
iabbrev betetr better
iabbrev bettre better
iabbrev bteter better
iabbrev ebtter better
iabbrev betewen between
iabbrev betwene between
iabbrev bewteen between
iabbrev bteween between
iabbrev ebtween between
iabbrev bgi big
iabbrev ibg big
iabbrev balck black
iabbrev blakc black
iabbrev blcak black
iabbrev lback black
iabbrev bok book
iabbrev obok book
iabbrev boht both
iabbrev btoh both
iabbrev obth both
iabbrev buisness business
iabbrev busness business
iabbrev bussiness business
iabbrev bsuiness business
iabbrev busienss business
iabbrev busniess business
iabbrev ubsiness business
iabbrev ubt but
iabbrev calandar calendar
iabbrev acll call
iabbrev clal call
iabbrev aclled called
iabbrev caled called
iabbrev caleld called
iabbrev callde called
iabbrev claled called
iabbrev caem came
iabbrev cmae came
iabbrev acn can
iabbrev cna can
iabbrev acr car
iabbrev cra car
iabbrev crae care
iabbrev carribbean Caribbean
iabbrev carribean Caribbean
iabbrev acse case
iabbrev csae case
iabbrev catechsim catechism
iabbrev cathecism catechism
iabbrev catagory category
iabbrev cemetary cemetery
iabbrev cahnge change
iabbrev chagne change
iabbrev chaneg change
iabbrev chnage change
iabbrev hcange change
iabbrev changable changeable
iabbrev cheif chief
iabbrev chidlren children
iabbrev chilrden children
iabbrev chlidren children
iabbrev cihldren children
iabbrev hcildren children
iabbrev chirst Christ
iabbrev ciyt city
iabbrev ctiy city
iabbrev icty city
iabbrev colleage colleague
iabbrev collegue colleague
iabbrev cmoe come
iabbrev coem come
iabbrev ocme come
iabbrev comming coming
iabbrev comamnd command
iabbrev commnad command
iabbrev comitted committed
iabbrev commited committed
iabbrev comittee committee
iabbrev commitee committee
iabbrev communnion communion
iabbrev comunion communion
iabbrev cmopany company
iabbrev comapny company
iabbrev compnay company
iabbrev copmany company
iabbrev ocmpany company
iabbrev concious conscious
iabbrev consious conscious
iabbrev concensus consensus
iabbrev colud could
iabbrev coudl could
iabbrev cuold could
iabbrev oculd could
iabbrev conutry country
iabbrev counrty country
iabbrev coutnry country
iabbrev cuontry country
iabbrev ocuntry country
iabbrev coruse course
iabbrev coures course
iabbrev cousre course
iabbrev cuorse course
iabbrev ocurse course
iabbrev corut court
iabbrev coutr court
iabbrev cuort court
iabbrev ocurt court
iabbrev curiousity curiosity
iabbrev ady day
iabbrev dya day
iabbrev adys days
iabbrev dasy days
iabbrev dyas days
iabbrev definately definitely
iabbrev definatly definitely
iabbrev definetly definitely
iabbrev definitly definitely
iabbrev diety deity
iabbrev desparate desperate
iabbrev ddi did
iabbrev idd did
iabbrev diferent different
iabbrev diffrent different
iabbrev dfiferent different
iabbrev difefrent different
iabbrev diffeernt different
iabbrev diffreent different
iabbrev idfferent different
iabbrev dilemna dilemma
iabbrev direcotry directory
iabbrev directroy directory
iabbrev disapoint disappoint
iabbrev dissapoint disappoint
iabbrev diong doing
iabbrev doign doing
iabbrev donig doing
iabbrev oding doing
iabbrev dnoe done
iabbrev doen done
iabbrev odne done
iabbrev donw down
iabbrev dwon down
iabbrev odwn down
iabbrev druing during
iabbrev duirng during
iabbrev durign during
iabbrev durnig during
iabbrev udring during
iabbrev aech each
iabbrev eahc each
iabbrev ecah each
iabbrev aerly early
iabbrev ealry early
iabbrev earyl early
iabbrev eraly early
iabbrev embarass embarrass
iabbrev enoguh enough
iabbrev enouhg enough
iabbrev enuogh enough
iabbrev eonugh enough
iabbrev neough enough
iabbrev enviornment environment
iabbrev enviroment environment
iabbrev ephiscopal Episcopal
iabbrev episcoapl Episcopal
iabbrev episocpal Episcopal
iabbrev epsicopal Episcopal
iabbrev episcopalain Episcopalian
iabbrev episcopallian Episcopalian
iabbrev eucharsit Eucharist
iabbrev euchrist Eucharist
iabbrev eevn even
iabbrev evne even
iabbrev veen even
iabbrev eevr ever
iabbrev evre ever
iabbrev eevry every
iabbrev eveyr every
iabbrev evrey every
iabbrev eevryone everyone
iabbrev everoyne everyone
iabbrev eveyrone everyone
iabbrev evreyone everyone
iabbrev veeryone everyone
iabbrev eevrything everything
iabbrev evertyhing everything
iabbrev eveyrthing everything
iabbrev evreything everything
iabbrev veerything everything
iabbrev excecute execute
iabbrev exectue execute
iabbrev excercise exercise
iabbrev exercize exercise
iabbrev existance existence
iabbrev existense existence
iabbrev expereince experience
iabbrev experiance experience
iabbrev afce face
iabbrev faec face
iabbrev fcae face
iabbrev afct fact
iabbrev fatc fact
iabbrev fcat fact
iabbrev familar familiar
iabbrev afmily family
iabbrev faimly family
iabbrev famiyl family
iabbrev famliy family
iabbrev fmaily family
iabbrev febuary February
iabbrev efel feel
iabbrev fel feel
iabbrev fele feel
iabbrev efw few
iabbrev fwe few
iabbrev finaly finally
iabbrev finnally finally
iabbrev fidn find
iabbrev fnid find
iabbrev ifnd find
iabbrev firts first
iabbrev fisrt first
iabbrev ifrst first
iabbrev fiev five
iabbrev fvie five
iabbrev ifve five
iabbrev flourescent fluorescent
iabbrev flolowing following
iabbrev folloiwng following
iabbrev follwoing following
iabbrev fololwing following
iabbrev ofllowing following
iabbrev ofr for
iabbrev foreing foreign
iabbrev foriegn foreign
iabbrev fourty forty
iabbrev fonud found
iabbrev foudn found
iabbrev fuond found
iabbrev ofund found
iabbrev foru four
iabbrev fuor four
iabbrev ofur four
iabbrev fere free
iabbrev fre free
iabbrev rfee free
iabbrev freind friend
iabbrev frined friend
iabbrev firends friends
iabbrev freinds friends
iabbrev friedns friends
iabbrev frineds friends
iabbrev rfiends friends
iabbrev frmo from
iabbrev rfom from
iabbrev flul full
iabbrev ful full
iabbrev ufll full
iabbrev fucntion function
iabbrev funciton function
iabbrev funtion function
iabbrev agme game
iabbrev gaem game
iabbrev gmae game
iabbrev agmes games
iabbrev gaems games
iabbrev gamse games
iabbrev gmaes games
iabbrev egneral general
iabbrev geenral general
iabbrev genreal general
iabbrev gneeral general
iabbrev egt get
iabbrev egtting getting
iabbrev getitng getting
iabbrev gettign getting
iabbrev gettnig getting
iabbrev gteting getting
iabbrev giev give
iabbrev gvie give
iabbrev igve give
iabbrev gievn given
iabbrev givne given
iabbrev gvien given
iabbrev igven given
iabbrev Gdo God
iabbrev giong going
iabbrev goign going
iabbrev gonig going
iabbrev oging going
iabbrev godo good
iabbrev ogod good
iabbrev gosple gospel
iabbrev gto got
iabbrev ogt got
iabbrev govenment government
iabbrev goverment government
iabbrev governmnet government
iabbrev goevrnment government
iabbrev govenrment government
iabbrev govrenment government
iabbrev gvoernment government
iabbrev ogvernment government
iabbrev grammer grammar
iabbrev gratefull grateful
iabbrev greatful grateful
iabbrev gerat great
iabbrev graet great
iabbrev rgeat great
iabbrev gorup group
iabbrev gropu group
iabbrev gruop group
iabbrev rgoup group
iabbrev gaurd guard
iabbrev ahd had
iabbrev hda had
iabbrev ahlf half
iabbrev hafl half
iabbrev hlaf half
iabbrev happend happened
iabbrev harrass harass
iabbrev ahrd hard
iabbrev hadr hard
iabbrev hrad hard
iabbrev ahs has
iabbrev hsa has
iabbrev ahve have
iabbrev haev have
iabbrev hvae have
iabbrev ahving having
iabbrev haivng having
iabbrev havign having
iabbrev havnig having
iabbrev hvaing having
iabbrev ehad head
iabbrev haed head
iabbrev heda head
iabbrev ehalth health
iabbrev haelth health
iabbrev healht health
iabbrev heatlh health
iabbrev helath health
iabbrev heighth height
iabbrev heigth height
iabbrev ehlp help
iabbrev hepl help
iabbrev hlep help
iabbrev hre her
iabbrev hree here
iabbrev hierachy hierarchy
iabbrev hgih high
iabbrev hihg high
iabbrev ihgh high
iabbrev hmi him
iabbrev hsi his
iabbrev ihs his
iabbrev hmoe home
iabbrev hoem home
iabbrev ohme home
iabbrev hoep hope
iabbrev hpoe hope
iabbrev ohpe hope
iabbrev hosue house
iabbrev houes house
iabbrev huose house
iabbrev ohuse house
iabbrev ohw how
iabbrev hoewver however
iabbrev howeevr however
iabbrev howveer however
iabbrev hwoever however
iabbrev ohwever however
iabbrev humerous humorous
iabbrev hygene hygiene
iabbrev imediately immediately
iabbrev immediatley immediately
iabbrev immediatly immediately
iabbrev improt import
iabbrev imoprtant important
iabbrev impotrant important
iabbrev improtant important
iabbrev ipmortant important
iabbrev miportant important
iabbrev icnluding including
iabbrev inclduing including
iabbrev inculding including
iabbrev inlcuding including
iabbrev nicluding including
iabbrev independance independence
iabbrev independant independent
iabbrev ifnormation information
iabbrev infomration information
iabbrev infromation information
iabbrev inofrmation information
iabbrev niformation information
iabbrev intresting interesting
iabbrev inot into
iabbrev itno into
iabbrev nito into
iabbrev jeuss Jesus
iabbrev jbo job
iabbrev ojb job
iabbrev jsut just
iabbrev ujst just
iabbrev ekep keep
iabbrev kepe keep
iabbrev iknd kind
iabbrev kidn kind
iabbrev knid kind
iabbrev knwo know
iabbrev konw know
iabbrev nkow know
iabbrev knowledg knowledge
iabbrev knowlege knowledge
iabbrev alst last
iabbrev lsat last
iabbrev laetr later
iabbrev latre later
iabbrev ltaer later
iabbrev alw law
iabbrev lwa law
iabbrev laest least
iabbrev leats least
iabbrev lesat least
iabbrev letf left
iabbrev lfet left
iabbrev lengh length
iabbrev lenght length
iabbrev elss less
iabbrev lses less
iabbrev elt let
iabbrev liason liaison
iabbrev libary library
iabbrev lisence license
iabbrev ilfe life
iabbrev lfie life
iabbrev ilke like
iabbrev lkie like
iabbrev ilne line
iabbrev lnie line
iabbrev ilttle little
iabbrev litle little
iabbrev litlte little
iabbrev littel little
iabbrev ltitle little
iabbrev litergy liturgy
iabbrev liturgey liturgy
iabbrev ilve live
iabbrev liev live
iabbrev lvie live
iabbrev lcoal local
iabbrev loacl local
iabbrev locla local
iabbrev olcal local
iabbrev lnog long
iabbrev logn long
iabbrev olng long
iabbrev olok look
iabbrev lokoing looking
iabbrev looikng looking
iabbrev lookign looking
iabbrev looknig looking
iabbrev oloking looking
iabbrev lto lot
iabbrev olt lot
iabbrev loev love
iabbrev lvoe love
iabbrev olve love
iabbrev amde made
iabbrev maed made
iabbrev mdae made
iabbrev maintainance maintenance
iabbrev maintenence maintenance
iabbrev amke make
iabbrev maek make
iabbrev mkae make
iabbrev amkes makes
iabbrev maeks makes
iabbrev makse makes
iabbrev mkaes makes
iabbrev amking making
iabbrev maikng making
iabbrev makign making
iabbrev maknig making
iabbrev mkaing making
iabbrev amn man
iabbrev mna man
iabbrev amny many
iabbrev mayn many
iabbrev mnay many
iabbrev mya may
iabbrev amybe maybe
iabbrev mabye maybe
iabbrev mayeb maybe
iabbrev myabe maybe
iabbrev eman mean
iabbrev maen mean
iabbrev emans means
iabbrev maens means
iabbrev measn means
iabbrev menas means
iabbrev medeval medieval
iabbrev emn men
iabbrev mne men
iabbrev imght might
iabbrev mgiht might
iabbrev migth might
iabbrev mihgt might
iabbrev milennium millennium
iabbrev millenium millennium
iabbrev mischievious mischievous
iabbrev mispell misspell
iabbrev mnoey money
iabbrev moeny money
iabbrev monye money
iabbrev omney money
iabbrev moer more
iabbrev mroe more
iabbrev omre more
iabbrev msot most
iabbrev omst most
iabbrev mcuh much
iabbrev muhc much
iabbrev umch much
iabbrev msuic music
iabbrev muisc music
iabbrev musci music
iabbrev umsic music
iabbrev msut must
iabbrev umst must
iabbrev anme name
iabbrev naem name
iabbrev nmae name
iabbrev antional national
iabbrev naitonal national
iabbrev natinoal national
iabbrev natoinal national
iabbrev ntaional national
iabbrev neccesary necessary
iabbrev neccessary necessary
iabbrev necesary necessary
iabbrev nede need
iabbrev enver never
iabbrev neevr never
iabbrev nevre never
iabbrev nveer never
iabbrev enw new
iabbrev nwe new
iabbrev enws news
iabbrev nesw news
iabbrev nwes news
iabbrev enxt next
iabbrev netx next
iabbrev nxet next
iabbrev neice niece
iabbrev inght night
iabbrev ngiht night
iabbrev nigth night
iabbrev nihgt night
iabbrev nto not
iabbrev nohting nothing
iabbrev nothnig nothing
iabbrev notihng nothing
iabbrev ntohing nothing
iabbrev onthing nothing
iabbrev noticable noticeable
iabbrev nwo now
iabbrev onw now
iabbrev nmuber number
iabbrev nubmer number
iabbrev numbre number
iabbrev numebr number
iabbrev unmber number
iabbrev ocassion occasion
iabbrev occassion occasion
iabbrev occured occurred
iabbrev ocurred occurred
iabbrev occurence occurrence
iabbrev ocurrence occurrence
iabbrev fof off
iabbrev lod old
iabbrev odl old
iabbrev noce once
iabbrev ocne once
iabbrev onec once
iabbrev oen one
iabbrev noly only
iabbrev olny only
iabbrev onyl only
iabbrev oepn open
iabbrev opne open
iabbrev poen open
iabbrev oportunity opportunity
iabbrev oppurtunity opportunity
iabbrev odrer order
iabbrev oredr order
iabbrev roder order
iabbrev ohter other
iabbrev otehr other
iabbrev othre other
iabbrev toher other
iabbrev ohters others
iabbrev otehrs others
iabbrev othesr others
iabbrev othres others
iabbrev tohers others
iabbrev oru our
iabbrev uor our
iabbrev otu out
iabbrev uot out
iabbrev oevr over
iabbrev ovre over
iabbrev voer over
iabbrev paralell parallel
iabbrev parrallel parallel
iabbrev paramater parameter
iabbrev paramter parameter
iabbrev aprt part
iabbrev patr part
iabbrev particulary particularly
iabbrev aprty party
iabbrev paryt party
iabbrev patry party
iabbrev praty party
iabbrev pentacost Pentecost
iabbrev epople people
iabbrev peolpe people
iabbrev peopel people
iabbrev pepole people
iabbrev poeple people
iabbrev epr per
iabbrev persistant persistent
iabbrev eprson person
iabbrev perosn person
iabbrev persno person
iabbrev pesron person
iabbrev preson person
iabbrev lpace place
iabbrev palce place
iabbrev plaec place
iabbrev plcae place
iabbrev lpay play
iabbrev plya play
iabbrev lpease please
iabbrev pelase please
iabbrev plaese please
iabbrev pleaes please
iabbrev plesae please
iabbrev opint point
iabbrev piont point
iabbrev poitn point
iabbrev ponit point
iabbrev posession possession
iabbrev possesion possession
iabbrev opst post
iabbrev psot post
iabbrev opwer power
iabbrev poewr power
iabbrev pwoer power
iabbrev preceed precede
iabbrev prefered preferred
iabbrev persident president
iabbrev preisdent president
iabbrev presdient president
iabbrev prseident president
iabbrev rpesident president
iabbrev pritn print
iabbrev privelege privilege
iabbrev privilage privilege
iabbrev priviledge privilege
iabbrev probabaly probably
iabbrev probaly probably
iabbrev pronounciation pronunciation
iabbrev propoganda propaganda
iabbrev pslam psalm
iabbrev pbulic public
iabbrev pubilc public
iabbrev publci public
iabbrev pulbic public
iabbrev upblic public
iabbrev publically publicly
iabbrev ptu put
iabbrev upt put
iabbrev pyhton Python
iabbrev pytohn Python
iabbrev questionaire questionnaire
iabbrev questionnare questionnaire
iabbrev erad read
iabbrev raed read
iabbrev reda read
iabbrev eral real
iabbrev rael real
iabbrev rela real
iabbrev realy really
iabbrev erally really
iabbrev raelly really
iabbrev realyl really
iabbrev relaly really
iabbrev receve receive
iabbrev recieve receive
iabbrev reccomend recommend
iabbrev reccommend recommend
iabbrev recomend recommend
iabbrev refered referred
iabbrev relavent relevant
iabbrev relevent relevant
iabbrev religous religious
iabbrev rember remember
iabbrev remeber remember
iabbrev resistence resistance
iabbrev restaraunt restaurant
iabbrev resturant restaurant
iabbrev ressurection resurrection
iabbrev resurection resurrection
iabbrev retrun return
iabbrev reutrn return
iabbrev rhythym rhythm
iabbrev rythm rhythm
iabbrev irght right
iabbrev rgiht right
iabbrev rigth right
iabbrev rihgt right
iabbrev rnu run
iabbrev sacremant sacrament
iabbrev asid said
iabbrev siad said
iabbrev asme same
iabbrev saem same
iabbrev smae same
iabbrev asy say
iabbrev sya say
iabbrev asys says
iabbrev sasy says
iabbrev syas says
iabbrev schedual schedule
iabbrev cshool school
iabbrev schol school
iabbrev scholo school
iabbrev scohol school
iabbrev shcool school
iabbrev sciprt script
iabbrev scirpt script
iabbrev scripure scripture
iabbrev scritpure scripture
iabbrev esason season
iabbrev saeson season
iabbrev seaosn season
iabbrev seasno season
iabbrev sesaon season
iabbrev escond second
iabbrev sceond second
iabbrev secnod second
iabbrev secodn second
iabbrev seocnd second
iabbrev esen seen
iabbrev sieze seize
iabbrev seperate separate
iabbrev seprate separate
iabbrev esrvice service
iabbrev serivce service
iabbrev servcie service
iabbrev sevrice service
iabbrev srevice service
iabbrev hse she
iabbrev hsould should
iabbrev sholud should
iabbrev shoudl should
iabbrev shuold should
iabbrev sohuld should
iabbrev hsow show
iabbrev shwo show
iabbrev sohw show
iabbrev isde side
iabbrev sdie side
iabbrev sied side
iabbrev similiar similar
iabbrev simmilar similar
iabbrev isnce since
iabbrev sicne since
iabbrev sinec since
iabbrev snice since
iabbrev msall small
iabbrev samll small
iabbrev smal small
iabbrev smlal small
iabbrev oscial social
iabbrev scoial social
iabbrev socail social
iabbrev socila social
iabbrev soical social
iabbrev osme some
iabbrev smoe some
iabbrev soem some
iabbrev osmeone someone
iabbrev smoeone someone
iabbrev soemone someone
iabbrev somenoe someone
iabbrev somoene someone
iabbrev osmething something
iabbrev smoething something
iabbrev soemthing something
iabbrev somehting something
iabbrev somtehing something
iabbrev speach speech
iabbrev satrt start
iabbrev statr start
iabbrev strat start
iabbrev tsart start
iabbrev staet state
iabbrev sttae state
iabbrev tsate state
iabbrev staets states
iabbrev statse states
iabbrev sttaes states
iabbrev tsates states
iabbrev sitll still
iabbrev stlil still
iabbrev tsill still
iabbrev sotp stop
iabbrev tsop stop
iabbrev sotry story
iabbrev stoyr story
iabbrev tsory story
iabbrev strenght strength
iabbrev strign string
iabbrev succesful successful
iabbrev successfull successful
iabbrev sucessful successful
iabbrev scuh such
iabbrev suhc such
iabbrev usch such
iabbrev supercede supersede
iabbrev spuport support
iabbrev supoprt support
iabbrev suppotr support
iabbrev supprot support
iabbrev uspport support
iabbrev srue sure
iabbrev usre sure
iabbrev suprise surprise
iabbrev sytem system
iabbrev sytsem system
iabbrev ssytem system
iabbrev sysetm system
iabbrev systme system
iabbrev ysstem system
iabbrev atke take
iabbrev taek take
iabbrev tkae take
iabbrev atlk talk
iabbrev takl talk
iabbrev tlak talk
iabbrev etam team
iabbrev taem team
iabbrev etll tell
iabbrev tlel tell
iabbrev temperture temperature
iabbrev htan than
iabbrev tahn than
iabbrev thna than
iabbrev htank thank
iabbrev tahnk thank
iabbrev thakn thank
iabbrev thnak thank
iabbrev htanks thanks
iabbrev tahnks thanks
iabbrev thakns thanks
iabbrev thansk thanks
iabbrev thnaks thanks
iabbrev htat that
iabbrev taht that
iabbrev thta that
iabbrev hte the
iabbrev teh the
iabbrev thier their
iabbrev hteir their
iabbrev tehir their
iabbrev theri their
iabbrev htem them
iabbrev tehm them
iabbrev thme them
iabbrev hten then
iabbrev tehn then
iabbrev thne then
iabbrev htere there
iabbrev tehre there
iabbrev theer there
iabbrev htese these
iabbrev tehse these
iabbrev thsee these
iabbrev htey they
iabbrev tehy they
iabbrev thye they
iabbrev hting thing
iabbrev thign thing
iabbrev thnig thing
iabbrev tihng thing
iabbrev htings things
iabbrev thigns things
iabbrev thinsg things
iabbrev thnigs things
iabbrev tihngs things
iabbrev htink think
iabbrev thikn think
iabbrev thnik think
iabbrev tihnk think
iabbrev htis this
iabbrev thsi this
iabbrev tihs this
iabbrev htose those
iabbrev thoes those
iabbrev thsoe those
iabbrev tohse those
iabbrev thogh though
iabbrev htough though
iabbrev thoguh though
iabbrev thouhg though
iabbrev thuogh though
iabbrev tohugh though
iabbrev thougth thought
iabbrev htought thought
iabbrev thoguht thought
iabbrev thouhgt thought
iabbrev thuoght thought
iabbrev tohught thought
iabbrev htree three
iabbrev thre three
iabbrev trhee three
iabbrev threshhold threshold
iabbrev throught through
iabbrev htrough through
iabbrev thorugh through
iabbrev throguh through
iabbrev thruogh through
iabbrev trhough through
iabbrev itme time
iabbrev tiem time
iabbrev tmie time
iabbrev itmes times
iabbrev tiems times
iabbrev timse times
iabbrev tmies times
iabbrev otday today
iabbrev tdoay today
iabbrev todya today
iabbrev otgether together
iabbrev tgoether together
iabbrev toegther together
iabbrev togehter together
iabbrev togteher together
iabbrev otld told
iabbrev tlod told
iabbrev todl told
iabbrev tommorow tomorrow
iabbrev tommorrow tomorrow
iabbrev tomorow tomorrow
iabbrev tounge tongue
iabbrev oto too
iabbrev otok took
iabbrev tok took
iabbrev toko took
iabbrev otp top
iabbrev tpo top
iabbrev truely truly
iabbrev rty try
iabbrev rtying trying
iabbrev triyng trying
iabbrev tryign trying
iabbrev trynig trying
iabbrev tyring trying
iabbrev wto two
iabbrev tyrany tyranny
iabbrev udner under
iabbrev undre under
iabbrev unedr under
iabbrev nuited united
iabbrev uinted united
iabbrev unietd united
iabbrev unitde united
iabbrev untill until
iabbrev nutil until
iabbrev unitl until
iabbrev untli until
iabbrev utnil until
iabbrev ues use
iabbrev uesd used
iabbrev usde used
iabbrev uisng using
iabbrev usign using
iabbrev usnig using
iabbrev vaccum vacuum
iabbrev vacume vacuum
iabbrev varaible variable
iabbrev vehical vehicle
iabbrev evry very
iabbrev veyr very
iabbrev vrey very
iabbrev ivdeo video
iabbrev vdieo video
iabbrev vidoe video
iabbrev viedo video
iabbrev awnt want
iabbrev watn want
iabbrev wnat want
iabbrev awr war
iabbrev wra war
iabbrev aws was
iabbrev wsa was
iabbrev awter water
iabbrev waetr water
iabbrev watre water
iabbrev wtaer water
iabbrev awy way
iabbrev wya way
iabbrev wedensday Wednesday
iabbrev wendesday Wednesday
iabbrev ewek week
iabbrev wek week
iabbrev weke week
iabbrev wierd weird
iabbrev ewll well
iabbrev wel well
iabbrev wlel well
iabbrev ewnt went
iabbrev wetn went
iabbrev wnet went
iabbrev ewre were
iabbrev wree were
iabbrev hwat what
iabbrev waht what
iabbrev whta what
iabbrev hwen when
iabbrev wehn when
iabbrev whne when
iabbrev hwere where
iabbrev wheer where
iabbrev whree where
iabbrev whereever wherever
iabbrev whcih which
iabbrev wich which
iabbrev hwich which
iabbrev whihc which
iabbrev wihch which
iabbrev hwile while
iabbrev whiel while
iabbrev whlie while
iabbrev wihle while
iabbrev hwite white
iabbrev whiet white
iabbrev whtie white
iabbrev wihte white
iabbrev hwo who
iabbrev woh who
iabbrev hwole whole
iabbrev whloe whole
iabbrev whoel whole
iabbrev wyh why
iabbrev widht width
iabbrev iwll will
iabbrev wlil will
iabbrev iwth with
iabbrev wiht with
iabbrev wtih with
iabbrev withold withhold
iabbrev iwthin within
iabbrev wihtin within
iabbrev withni within
iabbrev witihn within
iabbrev wtihin within
iabbrev iwthout without
iabbrev wihtout without
iabbrev withuot without
iabbrev witohut without
iabbrev wtihout without
iabbrev owmen women
iabbrev wmoen women
iabbrev woemn women
iabbrev womne women
iabbrev owrk work
iabbrev wokr work
iabbrev wrok work
iabbrev owrking working
iabbrev wokring working
iabbrev worikng working
iabbrev worknig working
iabbrev wroking working
iabbrev owrld world
iabbrev wolrd world
iabbrev wordl world
iabbrev wrold world
iabbrev owuld would
iabbrev wolud would
iabbrev woudl would
iabbrev wuold would
iabbrev writting writing
iabbrev eyar year
iabbrev yaer year
iabbrev yera year
iabbrev eyars years
iabbrev yaers years
iabbrev yeasr years
iabbrev yeras years
iabbrev eys yes
iabbrev yse yes
iabbrev eyt yet
iabbrev yte yet
iabbrev oyu you
iabbrev yuo you
iabbrev oyung young
iabbrev yonug young
iabbrev yougn young
iabbrev yuong young
iabbrev oyur your
iabbrev yoru your
iabbrev yuor your
iabbrev aebr aber
iabbrev baer aber
iabbrev Addresse Adresse
iabbrev Agression Aggression
iabbrev Akkussativ Akkusativ
iabbrev Akusativ Akkusativ
iabbrev Algorythmus Algorithmus
iabbrev alel alle
iabbrev lale alle
iabbrev alelm allem
iabbrev alem allem
iabbrev allme allem
iabbrev lalem allem
iabbrev aleln allen
iabbrev alen allen
iabbrev allne allen
iabbrev lalen allen
iabbrev alelrdings allerdings
iabbrev alledrings allerdings
iabbrev alleridngs allerdings
iabbrev allredings allerdings
iabbrev lalerdings allerdings
iabbrev alels alles
iabbrev allse alles
iabbrev lales alles
iabbrev asl als
iabbrev adnere andere
iabbrev andeer andere
iabbrev andree andere
iabbrev anedre andere
iabbrev nadere andere
iabbrev adneren anderen
iabbrev andeern anderen
iabbrev andreen anderen
iabbrev anedren anderen
iabbrev naderen anderen
iabbrev Appostel Apostel
iabbrev Abreit Arbeit
iabbrev Arbei Arbeit
iabbrev Arbeti Arbeit
iabbrev Arbiet Arbeit
iabbrev Arebit Arbeit
iabbrev abreiten arbeiten
iabbrev arbetien arbeiten
iabbrev arbieten arbeiten
iabbrev arebiten arbeiten
iabbrev rabeiten arbeiten
iabbrev Atr Art
iabbrev Athmosphäre Atmosphäre
iabbrev Atmospähre Atmosphäre
iabbrev acuh auch
iabbrev auhc auch
iabbrev uach auch
iabbrev afu auf
iabbrev uaf auf
iabbrev Auferstheung Auferstehung
iabbrev asu aus
iabbrev uas aus
iabbrev Ausprache Aussprache
iabbrev Barmherzigkiet Barmherzigkeit
iabbrev bie bei
iabbrev ebi bei
iabbrev bedie beide
iabbrev beied beide
iabbrev biede beide
iabbrev ebide beide
iabbrev beidne beiden
iabbrev beiedn beiden
iabbrev bieden beiden
iabbrev ebiden beiden
iabbrev bemi beim
iabbrev biem beim
iabbrev ebim beim
iabbrev bekmomen bekommen
iabbrev bekomemn bekommen
iabbrev beokmmen bekommen
iabbrev bkeommen bekommen
iabbrev ebkommen bekommen
iabbrev beerits bereits
iabbrev beretis bereits
iabbrev beriets bereits
iabbrev breeits bereits
iabbrev ebreits bereits
iabbrev beosnders besonders
iabbrev besnoders besonders
iabbrev besodners besonders
iabbrev bseonders besonders
iabbrev ebsonders besonders
iabbrev beser besser
iabbrev besesr besser
iabbrev bseser besser
iabbrev ebsser besser
iabbrev Bidl Bild
iabbrev Blid Bild
iabbrev bni bin
iabbrev bsi bis
iabbrev ibs bis
iabbrev bsit bist
iabbrev ibst bist
iabbrev bitet bitte
iabbrev btite bitte
iabbrev ibtte bitte
iabbrev belibt bleibt
iabbrev blebit bleibt
iabbrev bleitb bleibt
iabbrev lbeibt bleibt
iabbrev Charackter Charakter
iabbrev Karakter Charakter
iabbrev adbei dabei
iabbrev dabie dabei
iabbrev daebi dabei
iabbrev dbaei dabei
iabbrev adfür dafür
iabbrev dafrü dafür
iabbrev daüfr dafür
iabbrev dfaür dafür
iabbrev daimt damit
iabbrev damti damit
iabbrev dmait damit
iabbrev adnke danke
iabbrev dakne danke
iabbrev danek danke
iabbrev dnake danke
iabbrev adnn dann
iabbrev dnan dann
iabbrev adrauf darauf
iabbrev daaruf darauf
iabbrev darafu darauf
iabbrev daruaf darauf
iabbrev draauf darauf
iabbrev adrf darf
iabbrev dafr darf
iabbrev draf darf
iabbrev adrüber darüber
iabbrev darbüer darüber
iabbrev darüebr darüber
iabbrev daürber darüber
iabbrev draüber darüber
iabbrev dsa das
iabbrev adss dass
iabbrev dsas dass
iabbrev advon davon
iabbrev daovn davon
iabbrev davno davon
iabbrev dvaon davon
iabbrev adzu dazu
iabbrev dauz dazu
iabbrev dzau dazu
iabbrev deni dein
iabbrev dien dein
iabbrev edin dein
iabbrev deien deine
iabbrev denie deine
iabbrev edine deine
iabbrev dme dem
iabbrev edm dem
iabbrev dne den
iabbrev deenn denen
iabbrev denne denen
iabbrev dneen denen
iabbrev ednen denen
iabbrev dnen denn
iabbrev ednn denn
iabbrev edr der
iabbrev deern deren
iabbrev derne deren
iabbrev dreen deren
iabbrev edren deren
iabbrev dse des
iabbrev dehsalb deshalb
iabbrev desahlb deshalb
iabbrev deshlab deshalb
iabbrev dsehalb deshalb
iabbrev edshalb deshalb
iabbrev detusch deutsch
iabbrev deustch deutsch
iabbrev detusche deutsche
iabbrev deustche deutsche
iabbrev deutcshe deutsche
iabbrev duetsche deutsche
iabbrev edutsche deutsche
iabbrev detuschen deutschen
iabbrev deustchen deutschen
iabbrev deutcshen deutschen
iabbrev duetschen deutschen
iabbrev edutschen deutschen
iabbrev Detuschland Deutschland
iabbrev Deutshcland Deutschland
iabbrev Deustchland Deutschland
iabbrev Deutcshland Deutschland
iabbrev Duetschland Deutschland
iabbrev dcih dich
iabbrev dihc dich
iabbrev idch dich
iabbrev deis dies
iabbrev deise diese
iabbrev diees diese
iabbrev disee diese
iabbrev idese diese
iabbrev deisem diesem
iabbrev dieesm diesem
iabbrev diesme diesem
iabbrev diseem diesem
iabbrev idesem diesem
iabbrev deisen diesen
iabbrev dieesn diesen
iabbrev diesne diesen
iabbrev diseen diesen
iabbrev idesen diesen
iabbrev deiser dieser
iabbrev dieesr dieser
iabbrev diesre dieser
iabbrev diseer dieser
iabbrev ideser dieser
iabbrev deises dieses
iabbrev dieess dieses
iabbrev diesse dieses
iabbrev disees dieses
iabbrev ideses dieses
iabbrev Dilletant Dilettant
iabbrev dri dir
iabbrev idr dir
iabbrev dcoh doch
iabbrev dohc doch
iabbrev odch doch
iabbrev dotr dort
iabbrev drot dort
iabbrev odrt dort
iabbrev deri drei
iabbrev drie drei
iabbrev rdei drei
iabbrev druch durch
iabbrev ducrh durch
iabbrev durhc durch
iabbrev udrch durch
iabbrev eebn eben
iabbrev ebenfals ebenfalls
iabbrev egienen eigenen
iabbrev eiegnen eigenen
iabbrev eigeenn eigenen
iabbrev eigneen eigenen
iabbrev iegenen eigenen
iabbrev eigendlich eigentlich
iabbrev eigntlich eigentlich
iabbrev egientlich eigentlich
iabbrev eiegntlich eigentlich
iabbrev eigetnlich eigentlich
iabbrev eignetlich eigentlich
iabbrev iegentlich eigentlich
iabbrev eni ein
iabbrev ien ein
iabbrev eien eine
iabbrev enie eine
iabbrev iene eine
iabbrev eienm einem
iabbrev einme einem
iabbrev eniem einem
iabbrev ienem einem
iabbrev eienn einen
iabbrev einne einen
iabbrev enien einen
iabbrev ienen einen
iabbrev eienr einer
iabbrev einre einer
iabbrev enier einer
iabbrev iener einer
iabbrev eiens eines
iabbrev einse eines
iabbrev enies eines
iabbrev ienes eines
iabbrev eifnach einfach
iabbrev einafch einfach
iabbrev einfcah einfach
iabbrev enifach einfach
iabbrev ienfach einfach
iabbrev eiinge einige
iabbrev eingie einige
iabbrev einieg einige
iabbrev eniige einige
iabbrev ienige einige
iabbrev eimnal einmal
iabbrev einaml einmal
iabbrev einmla einmal
iabbrev enimal einmal
iabbrev ienmal einmal
iabbrev Edne Ende
iabbrev entgültig endgültig
iabbrev Entgeld Entgelt
iabbrev Entschludigung Entschuldigung
iabbrev Entschuldigng Entschuldigung
iabbrev erts erst
iabbrev esrt erst
iabbrev erset erste
iabbrev ertse erste
iabbrev esrte erste
iabbrev ersetn ersten
iabbrev erstne ersten
iabbrev ertsen ersten
iabbrev esrten ersten
iabbrev etaw etwa
iabbrev ewta etwa
iabbrev tewa etwa
iabbrev etaws etwas
iabbrev etwsa etwas
iabbrev ewtas etwas
iabbrev tewas etwas
iabbrev ecuh euch
iabbrev euhc euch
iabbrev uech euch
iabbrev Eruo Euro
iabbrev Euor Euro
iabbrev Evangelim Evangelium
iabbrev Evanglium Evangelium
iabbrev Fal Fall
iabbrev Flal Fall
iabbrev Faimlie Familie
iabbrev Famiile Familie
iabbrev Familei Familie
iabbrev Famliie Familie
iabbrev Fmailie Familie
iabbrev afst fast
iabbrev fsat fast
iabbrev fidnen finden
iabbrev findne finden
iabbrev finedn finden
iabbrev fniden finden
iabbrev ifnden finden
iabbrev fidnet findet
iabbrev findte findet
iabbrev finedt findet
iabbrev fnidet findet
iabbrev ifndet findet
iabbrev fraeg frage
iabbrev frgae frage
iabbrev rfage frage
iabbrev fargen fragen
iabbrev fraegn fragen
iabbrev fragne fragen
iabbrev frgaen fragen
iabbrev rfagen fragen
iabbrev Faru Frau
iabbrev Frua Frau
iabbrev Faruen Frauen
iabbrev Fraeun Frauen
iabbrev Fraue Frauen
iabbrev Fraune Frauen
iabbrev Fruaen Frauen
iabbrev Frühstuck Frühstück
iabbrev frü für
iabbrev üfr für
iabbrev gba gab
iabbrev Gallerie Galerie
iabbrev agnz ganz
iabbrev gazn ganz
iabbrev gnaz ganz
iabbrev agnze ganze
iabbrev ganez ganze
iabbrev gazne ganze
iabbrev gnaze ganze
iabbrev agnzen ganzen
iabbrev ganezn ganzen
iabbrev ganzne ganzen
iabbrev gaznen ganzen
iabbrev gnazen ganzen
iabbrev agr gar
iabbrev gra gar
iabbrev egben geben
iabbrev gbeen geben
iabbrev gebne geben
iabbrev geebn geben
iabbrev Gbeet Gebet
iabbrev Geburstag Geburtstag
iabbrev geegn gegen
iabbrev gegne gegen
iabbrev ggeen gegen
iabbrev eghen gehen
iabbrev geehn gehen
iabbrev gehne gehen
iabbrev gheen gehen
iabbrev eght geht
iabbrev geth geht
iabbrev ghet geht
iabbrev eghört gehört
iabbrev gehröt gehört
iabbrev gehötr gehört
iabbrev geöhrt gehört
iabbrev gheört gehört
iabbrev Gedl Geld
iabbrev Gled Geld
iabbrev egmacht gemacht
iabbrev geamcht gemacht
iabbrev gemahct gemacht
iabbrev gemcaht gemacht
iabbrev gmeacht gemacht
iabbrev egnau genau
iabbrev geanu genau
iabbrev gneau genau
iabbrev Genetiv Genitiv
iabbrev egrade gerade
iabbrev gearde gerade
iabbrev geraed gerade
iabbrev gerdae gerade
iabbrev greade gerade
iabbrev egrne gerne
iabbrev geren gerne
iabbrev grene gerne
iabbrev egsagt gesagt
iabbrev geasgt gesagt
iabbrev gesatg gesagt
iabbrev gesgat gesagt
iabbrev gseagt gesagt
iabbrev Gecshichte Geschichte
iabbrev Geschcihte Geschichte
iabbrev Gescihchte Geschichte
iabbrev Geshcichte Geschichte
iabbrev Gsechichte Geschichte
iabbrev egsehen gesehen
iabbrev geeshen gesehen
iabbrev geseehn gesehen
iabbrev gesheen gesehen
iabbrev gseehen gesehen
iabbrev egwesen gewesen
iabbrev geewsen gewesen
iabbrev geweesn gewesen
iabbrev gewseen gewesen
iabbrev gweesen gewesen
iabbrev gitb gibt
iabbrev igbt gibt
iabbrev gign ging
iabbrev gnig ging
iabbrev igng ging
iabbrev galube glaube
iabbrev glabue glaube
iabbrev glaueb glaube
iabbrev gluabe glaube
iabbrev lgaube glaube
iabbrev gelich gleich
iabbrev glecih gleich
iabbrev gleihc gleich
iabbrev gliech gleich
iabbrev lgeich gleich
iabbrev Gottesdeinst Gottesdienst
iabbrev Gramatik Grammatik
iabbrev Grammattik Grammatik
iabbrev gtu gut
iabbrev gtue gute
iabbrev ugte gute
iabbrev gtuen guten
iabbrev guetn guten
iabbrev gutne guten
iabbrev ugten guten
iabbrev ahb hab
iabbrev hba hab
iabbrev ahbe habe
iabbrev haeb habe
iabbrev hbae habe
iabbrev ahben haben
iabbrev habne haben
iabbrev haebn haben
iabbrev hbaen haben
iabbrev ahst hast
iabbrev hsat hast
iabbrev aht hat
iabbrev hta hat
iabbrev ahtte hatte
iabbrev hatet hatte
iabbrev htate hatte
iabbrev ahtten hatten
iabbrev haten hatten
iabbrev hatetn hatten
iabbrev hattne hatten
iabbrev htaten hatten
iabbrev Hasu Haus
iabbrev Huas Haus
iabbrev Hieliger Heiliger
iabbrev ehute heute
iabbrev hetue heute
iabbrev heuet heute
iabbrev huete heute
iabbrev iher hier
iabbrev hni hin
iabbrev htäte hätte
iabbrev häte hätte
iabbrev hätet hätte
iabbrev ähtte hätte
iabbrev cih ich
iabbrev ihc ich
iabbrev imh ihm
iabbrev inh ihn
iabbrev hinen ihnen
iabbrev ihenn ihnen
iabbrev ihnne ihnen
iabbrev inhen ihnen
iabbrev hir ihr
iabbrev irh ihr
iabbrev irhe ihre
iabbrev hirem ihrem
iabbrev iherm ihrem
iabbrev ihrme ihrem
iabbrev irhem ihrem
iabbrev hiren ihren
iabbrev ihern ihren
iabbrev ihrne ihren
iabbrev irhen ihren
iabbrev iherr ihrer
iabbrev ihrre ihrer
iabbrev irher ihrer
iabbrev imemr immer
iabbrev imer immer
iabbrev immre immer
iabbrev Ingeneur Ingenieur
iabbrev Ingenier Ingenieur
iabbrev isn ins
iabbrev nis ins
iabbrev interesant interessant
iabbrev interessannt interessant
iabbrev interresant interessant
iabbrev Interresse Interesse
iabbrev Jarh Jahr
iabbrev Jhar Jahr
iabbrev Jaher Jahre
iabbrev Jarhe Jahre
iabbrev Jhare Jahre
iabbrev Jahern Jahren
iabbrev Jahrne Jahren
iabbrev Jarhen Jahren
iabbrev Jharen Jahren
iabbrev ejden jeden
iabbrev jdeen jeden
iabbrev jedne jeden
iabbrev jeedn jeden
iabbrev ejder jeder
iabbrev jdeer jeder
iabbrev jedre jeder
iabbrev jeedr jeder
iabbrev ejdoch jedoch
iabbrev jdeoch jedoch
iabbrev jedcoh jedoch
iabbrev jedohc jedoch
iabbrev jeodch jedoch
iabbrev ejmand jemand
iabbrev jeamnd jemand
iabbrev jemadn jemand
iabbrev jemnad jemand
iabbrev jmeand jemand
iabbrev ejtzt jetzt
iabbrev jettz jetzt
iabbrev jeztt jetzt
iabbrev jtezt jetzt
iabbrev akm kam
iabbrev kma kam
iabbrev aknn kann
iabbrev knan kann
iabbrev aknnst kannst
iabbrev kannts kannst
iabbrev kansnt kannst
iabbrev kanst kannst
iabbrev knanst kannst
iabbrev Karrikatur Karikatur
iabbrev Katastrofe Katastrophe
iabbrev ekin kein
iabbrev keni kein
iabbrev ekine keine
iabbrev keien keine
iabbrev kenie keine
iabbrev ekinen keinen
iabbrev keienn keinen
iabbrev keinne keinen
iabbrev kenien keinen
iabbrev Kidner Kinder
iabbrev Kinde Kinder
iabbrev Kindre Kinder
iabbrev Kinedr Kinder
iabbrev Knider Kinder
iabbrev Krihce Kirche
iabbrev kalr klar
iabbrev klra klar
iabbrev lkar klar
iabbrev keline kleine
iabbrev klenie kleine
iabbrev kliene kleine
iabbrev lkeine kleine
iabbrev Kommitee Komitee
iabbrev kmomen kommen
iabbrev komemn kommen
iabbrev komen kommen
iabbrev kommne kommen
iabbrev okmmen kommen
iabbrev Komission Kommission
iabbrev Kommision Kommission
iabbrev kmomt kommt
iabbrev komt kommt
iabbrev komtm kommt
iabbrev okmmt kommt
iabbrev Kommunkation Kommunikation
iabbrev Komunikation Kommunikation
iabbrev Konkurenz Konkurrenz
iabbrev knonte konnte
iabbrev konnet konnte
iabbrev konte konnte
iabbrev kontne konnte
iabbrev oknnte konnte
iabbrev kruz kurz
iabbrev kuzr kurz
iabbrev ukrz kurz
iabbrev knönen können
iabbrev könen können
iabbrev könenn können
iabbrev könnne können
iabbrev öknnen können
iabbrev knönte könnte
iabbrev könnet könnte
iabbrev könte könnte
iabbrev köntne könnte
iabbrev öknnte könnte
iabbrev Ladn Land
iabbrev Lnad Land
iabbrev alnge lange
iabbrev lagne lange
iabbrev laneg lange
iabbrev lnage lange
iabbrev alssen lassen
iabbrev lasesn lassen
iabbrev lassne lassen
iabbrev lsasen lassen
iabbrev elben leben
iabbrev lbeen leben
iabbrev lebne leben
iabbrev leebn leben
iabbrev Leherer Lehrer
iabbrev eltzten letzten
iabbrev lettzen letzten
iabbrev letzetn letzten
iabbrev leztten letzten
iabbrev ltezten letzten
iabbrev Letue Leute
iabbrev Leuet Leute
iabbrev Luete Leute
iabbrev ilebe liebe
iabbrev libee liebe
iabbrev lieeb liebe
iabbrev ilegt liegt
iabbrev leigt liegt
iabbrev lietg liegt
iabbrev liget liegt
iabbrev Litturgie Liturgie
iabbrev Lizens Lizenz
iabbrev lsäst lässt
iabbrev läst lässt
iabbrev lästs lässt
iabbrev älsst lässt
iabbrev amchen machen
iabbrev macehn machen
iabbrev machne machen
iabbrev mahcen machen
iabbrev mcahen machen
iabbrev amcht macht
iabbrev macth macht
iabbrev mahct macht
iabbrev mcaht macht
iabbrev aml mal
iabbrev Mnan Mann
iabbrev Maschiene Maschine
iabbrev Mathemathik Mathematik
iabbrev emhr mehr
iabbrev merh mehr
iabbrev mher mehr
iabbrev emin mein
iabbrev meni mein
iabbrev emine meine
iabbrev meien meine
iabbrev menie meine
iabbrev meienm meinem
iabbrev meinme meinem
iabbrev meniem meinem
iabbrev mienem meinem
iabbrev eminen meinen
iabbrev meienn meinen
iabbrev meinne meinen
iabbrev menien meinen
iabbrev eminer meiner
iabbrev meienr meiner
iabbrev meinre meiner
iabbrev menier meiner
iabbrev miener meiner
iabbrev Mencshen Menschen
iabbrev Menscehn Menschen
iabbrev Menshcen Menschen
iabbrev Mesnchen Menschen
iabbrev Mneschen Menschen
iabbrev imch mich
iabbrev mcih mich
iabbrev mihc mich
iabbrev Mintuen Minuten
iabbrev Minuetn Minuten
iabbrev Minutne Minuten
iabbrev Miunten Minuten
iabbrev Mniuten Minuten
iabbrev imr mir
iabbrev imt mit
iabbrev mti mit
iabbrev Mitwoch Mittwoch
iabbrev mogren morgen
iabbrev moregn morgen
iabbrev morgne morgen
iabbrev mrogen morgen
iabbrev omrgen morgen
iabbrev msus muss
iabbrev umss muss
iabbrev mcöhte möchte
iabbrev möchet möchte
iabbrev möcthe möchte
iabbrev möhcte möchte
iabbrev ömchte möchte
iabbrev mgölich möglich
iabbrev mögilch möglich
iabbrev möglcih möglich
iabbrev mölgich möglich
iabbrev ömglich möglich
iabbrev msüsen müssen
iabbrev müsen müssen
iabbrev müsesn müssen
iabbrev müssne müssen
iabbrev ümssen müssen
iabbrev anch nach
iabbrev nahc nach
iabbrev ncah nach
iabbrev antürlich natürlich
iabbrev natrülich natürlich
iabbrev natülrich natürlich
iabbrev naütrlich natürlich
iabbrev ntaürlich natürlich
iabbrev enben neben
iabbrev nbeen neben
iabbrev nebne neben
iabbrev neebn neben
iabbrev enhmen nehmen
iabbrev nehemn nehmen
iabbrev nehmne nehmen
iabbrev nemhen nehmen
iabbrev nhemen nehmen
iabbrev enin nein
iabbrev neni nein
iabbrev nien nein
iabbrev enue neue
iabbrev neeu neue
iabbrev nuee neue
iabbrev enuen neuen
iabbrev neeun neuen
iabbrev neune neuen
iabbrev nueen neuen
iabbrev incht nicht
iabbrev nciht nicht
iabbrev nicth nicht
iabbrev nihct nicht
iabbrev inchts nichts
iabbrev ncihts nichts
iabbrev nichst nichts
iabbrev nicths nichts
iabbrev nihcts nichts
iabbrev nei nie
iabbrev ncoh noch
iabbrev nohc noch
iabbrev onch noch
iabbrev nnu nun
iabbrev unn nun
iabbrev nru nur
iabbrev unr nur
iabbrev nähmlich nämlich
iabbrev nämmlich nämlich
iabbrev odre oder
iabbrev oedr oder
iabbrev fot oft
iabbrev otf oft
iabbrev ohen ohne
iabbrev onhe ohne
iabbrev apar paar
iabbrev Filosofie Philosophie
iabbrev Philosphie Philosophie
iabbrev Paltz Platz
iabbrev Plazt Platz
iabbrev Pltaz Platz
iabbrev Ploizei Polizei
iabbrev Poilzei Polizei
iabbrev Poliezi Polizei
iabbrev Polizie Polizei
iabbrev Polziei Polizei
iabbrev Psycholgie Psychologie
iabbrev ercht recht
iabbrev rceht recht
iabbrev recth recht
iabbrev rehct recht
iabbrev Rechtschreibng Rechtschreibung
iabbrev Reflektion Reflexion
iabbrev Reperatur Reparatur
iabbrev Rethorik Rhetorik
iabbrev Rhytmus Rhythmus
iabbrev Rythmus Rhythmus
iabbrev irchtig richtig
iabbrev rcihtig richtig
iabbrev richitg richtig
iabbrev ricthig richtig
iabbrev rihctig richtig
iabbrev Rückrad Rückgrat
iabbrev asgen sagen
iabbrev saegn sagen
iabbrev sagne sagen
iabbrev sgaen sagen
iabbrev asgt sagt
iabbrev satg sagt
iabbrev sgat sagt
iabbrev asgte sagte
iabbrev saget sagte
iabbrev satge sagte
iabbrev sgate sagte
iabbrev Satelit Satellit
iabbrev Sattelit Satellit
iabbrev cshnell schnell
iabbrev schenll schnell
iabbrev schnlel schnell
iabbrev scnhell schnell
iabbrev shcnell schnell
iabbrev cshon schon
iabbrev schno schon
iabbrev scohn schon
iabbrev shcon schon
iabbrev cshön schön
iabbrev schnö schön
iabbrev scöhn schön
iabbrev shcön schön
iabbrev eshen sehen
iabbrev seehn sehen
iabbrev eshr sehr
iabbrev serh sehr
iabbrev esi sei
iabbrev esin sein
iabbrev seni sein
iabbrev esine seine
iabbrev senie seine
iabbrev siene seine
iabbrev esinem seinem
iabbrev seienm seinem
iabbrev seinme seinem
iabbrev seniem seinem
iabbrev sienem seinem
iabbrev esinen seinen
iabbrev seienn seinen
iabbrev seinne seinen
iabbrev senien seinen
iabbrev sienen seinen
iabbrev esiner seiner
iabbrev seienr seiner
iabbrev seinre seiner
iabbrev senier seiner
iabbrev siener seiner
iabbrev esit seit
iabbrev seti seit
iabbrev siet seit
iabbrev Seiet Seite
iabbrev Setie Seite
iabbrev eslbst selbst
iabbrev seblst selbst
iabbrev selbts selbst
iabbrev selsbt selbst
iabbrev slebst selbst
iabbrev seperat separat
iabbrev scih sich
iabbrev sihc sich
iabbrev ischer sicher
iabbrev sciher sicher
iabbrev sicehr sicher
iabbrev sihcer sicher
iabbrev ise sie
iabbrev iseht sieht
iabbrev seiht sieht
iabbrev sieth sieht
iabbrev sihet sieht
iabbrev isnd sind
iabbrev sidn sind
iabbrev snid sind
iabbrev osgar sogar
iabbrev sgoar sogar
iabbrev soagr sogar
iabbrev sogra sogar
iabbrev osll soll
iabbrev slol soll
iabbrev osllen sollen
iabbrev slolen sollen
iabbrev soleln sollen
iabbrev solen sollen
iabbrev sollne sollen
iabbrev osllte sollte
iabbrev slolte sollte
iabbrev sollet sollte
iabbrev solte sollte
iabbrev soltle sollte
iabbrev osllten sollten
iabbrev slolten sollten
iabbrev solletn sollten
iabbrev solltne sollten
iabbrev soltlen sollten
iabbrev osndern sondern
iabbrev snodern sondern
iabbrev sodnern sondern
iabbrev sondren sondern
iabbrev sonedrn sondern
iabbrev osnst sonst
iabbrev snost sonst
iabbrev sonts sonst
iabbrev sosnt sonst
iabbrev oswie sowie
iabbrev soiwe sowie
iabbrev sowei sowie
iabbrev swoie sowie
iabbrev Sipel Spiel
iabbrev Speil Spiel
iabbrev psielen spielen
iabbrev sipelen spielen
iabbrev speilen spielen
iabbrev spieeln spielen
iabbrev spileen spielen
iabbrev Sprichtwort Sprichwort
iabbrev psäter später
iabbrev sptäer später
iabbrev späetr später
iabbrev spätre später
iabbrev säpter später
iabbrev Satdt Stadt
iabbrev Statd Stadt
iabbrev Stdat Stadt
iabbrev Standart Standard
iabbrev sattt statt
iabbrev sttat statt
iabbrev tsatt statt
iabbrev sethen stehen
iabbrev steehn stehen
iabbrev stehne stehen
iabbrev stheen stehen
iabbrev tsehen stehen
iabbrev setht steht
iabbrev steth steht
iabbrev sthet steht
iabbrev tseht steht
iabbrev Symphatie Sympathie
iabbrev Tga Tag
iabbrev Teli Teil
iabbrev Tiel Teil
iabbrev Terasse Terrasse
iabbrev Theather Theater
iabbrev Theolgie Theologie
iabbrev Theolgoie Theologie
iabbrev Tolleranz Toleranz
iabbrev tnu tun
iabbrev utn tun
iabbrev tötlich tödlich
iabbrev Urh Uhr
iabbrev nud und
iabbrev udn und
iabbrev usn uns
iabbrev nuser unser
iabbrev unesr unser
iabbrev usner unser
iabbrev nusere unsere
iabbrev unesre unsere
iabbrev unseer unsere
iabbrev unsree unsere
iabbrev usnere unsere
iabbrev nuter unter
iabbrev unetr unter
iabbrev untre unter
iabbrev utner unter
iabbrev Vakum Vakuum
iabbrev ivel viel
iabbrev ivele viele
iabbrev veile viele
iabbrev vieel viele
iabbrev vilee viele
iabbrev ivelen vielen
iabbrev veilen vielen
iabbrev vieeln vielen
iabbrev vielne vielen
iabbrev vileen vielen
iabbrev vieleicht vielleicht
iabbrev vielleict vielleicht
iabbrev vileicht vielleicht
iabbrev ivelleicht vielleicht
iabbrev veilleicht vielleicht
iabbrev vielelicht vielleicht
iabbrev vielliecht vielleicht
iabbrev vileleicht vielleicht
iabbrev iver vier
iabbrev veir vier
iabbrev ovm vom
iabbrev vmo vom
iabbrev ovn von
iabbrev vno von
iabbrev ovr vor
iabbrev vro vor
iabbrev vorraus voraus
iabbrev Vorraussetzung Voraussetzung
iabbrev wahrscheinlihc wahrscheinlich
iabbrev warscheinlich wahrscheinlich
iabbrev awren waren
iabbrev waern waren
iabbrev wraen waren
iabbrev awrum warum
iabbrev warmu warum
iabbrev waurm warum
iabbrev wraum warum
iabbrev wge weg
iabbrev ewgen wegen
iabbrev weegn wegen
iabbrev wegne wegen
iabbrev wgeen wegen
iabbrev Weihnahcten Weihnachten
iabbrev Weinachten Weihnachten
iabbrev ewil weil
iabbrev weli weil
iabbrev wiel weil
iabbrev ewit weit
iabbrev weti weit
iabbrev wiet weit
iabbrev ewiter weiter
iabbrev weietr weiter
iabbrev weitre weiter
iabbrev wetier weiter
iabbrev wieter weiter
iabbrev ewitere weitere
iabbrev weietre weitere
iabbrev weitree weitere
iabbrev wetiere weitere
iabbrev wietere weitere
iabbrev ewlche welche
iabbrev weclhe welche
iabbrev welceh welche
iabbrev welhce welche
iabbrev wleche welche
iabbrev Wetl Welt
iabbrev Wlet Welt
iabbrev ewnig wenig
iabbrev weing wenig
iabbrev wengi wenig
iabbrev wneig wenig
iabbrev ewniger weniger
iabbrev weinger weniger
iabbrev wengier weniger
iabbrev weniegr weniger
iabbrev wneiger weniger
iabbrev ewnn wenn
iabbrev wnen wenn
iabbrev ewr wer
iabbrev wre wer
iabbrev ewrde werde
iabbrev wedre werde
iabbrev wered werde
iabbrev wrede werde
iabbrev ewrden werden
iabbrev wedren werden
iabbrev werdne werden
iabbrev weredn werden
iabbrev wreden werden
iabbrev wiederspiegeln widerspiegeln
iabbrev Wiederspruch Widerspruch
iabbrev Wiederstand Widerstand
iabbrev iwe wie
iabbrev iweder wieder
iabbrev weider wieder
iabbrev wideer wieder
iabbrev wiedre wieder
iabbrev wieedr wieder
iabbrev Widersehen Wiedersehen
iabbrev iwr wir
iabbrev wri wir
iabbrev iwrd wird
iabbrev widr wird
iabbrev wrid wird
iabbrev iwrklich wirklich
iabbrev wikrlich wirklich
iabbrev wirkilch wirklich
iabbrev wirlkich wirklich
iabbrev wriklich wirklich
iabbrev iwssen wissen
iabbrev wisen wissen
iabbrev wisesn wissen
iabbrev wissne wissen
iabbrev wsisen wissen
iabbrev owhl wohl
iabbrev whol wohl
iabbrev wolh wohl
iabbrev owllen wollen
iabbrev wlolen wollen
iabbrev woleln wollen
iabbrev wolen wollen
iabbrev wollne wollen
iabbrev owllte wollte
iabbrev wlolte wollte
iabbrev wollet wollte
iabbrev wolte wollte
iabbrev woltle wollte
iabbrev owrden worden
iabbrev wodren worden
iabbrev wordne worden
iabbrev woredn worden
iabbrev wroden worden
iabbrev uwrde wurde
iabbrev wrude wurde
iabbrev wudre wurde
iabbrev wured wurde
iabbrev uwrden wurden
iabbrev wruden wurden
iabbrev wudren wurden
iabbrev wurdne wurden
iabbrev wuredn wurden
iabbrev whärend während
iabbrev wähernd während
iabbrev währned während
iabbrev wärhend während
iabbrev äwhrend während
iabbrev wräe wäre
iabbrev wäer wäre
iabbrev äwre wäre
iabbrev Wörtebuch Wörterbuch
iabbrev wrüde würde
iabbrev wüdre würde
iabbrev würed würde
iabbrev üwrde würde
iabbrev Zeti Zeit
iabbrev Ziet Zeit
iabbrev Ziehl Ziel
iabbrev uzm zum
iabbrev zmu zum
iabbrev uzr zur
iabbrev zru zur
iabbrev uzrück zurück
iabbrev zruück zurück
iabbrev zurcük zurück
iabbrev zurükc zurück
iabbrev zuürck zurück
iabbrev uzsammen zusammen
iabbrev zsuammen zusammen
iabbrev zuasmmen zusammen
iabbrev zusamemn zusammen
iabbrev zusmamen zusammen
iabbrev wzar zwar
iabbrev zawr zwar
iabbrev zwra zwar
iabbrev wzei zwei
iabbrev zewi zwei
iabbrev zwie zwei
iabbrev wzischen zwischen
iabbrev ziwschen zwischen
iabbrev zwicshen zwischen
iabbrev zwishcen zwischen
iabbrev zwsichen zwischen
iabbrev büer über
iabbrev übre über
iabbrev üebr über
iabbrev Übersetzng Übersetzung
iabbrev Übersezung Übersetzung
